version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app # Set working directory to where the Flask app resides

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A worker.tasks.celery worker --loglevel=info
    depends_on:
      - redis
      - app
    working_dir: /app/worker

  redis:
    image: redis:bookworm
    ports:
      - "6379:6379"
